### ISSUE TITLE
Please specify the license your packages are released under

### ISSUE THREAD

**Issue by tarsius** [jave/dired-sequence#1]
Could you please specify the license used by your Emacs packages?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the text of the GPL-3. But if you only add that file, then the "or (at your option) any later version" bit won't be known.

If this is all to noisy, then you could also add this to the header:

```
;; License: GPL-3+
```
Please adjust these packages accordingly: `dna-debug`, `dragbox`, `emmental`, `emsane`, `pocketcompletion`, `sh-proxy`, and `zen-mode`.

**Comment by jave** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> Could you please specify the license used by your Emacs packages?
>
> Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:


Thanks for the information.

I will use ;; License: GPL-3+

I'm thinking of moving my things to Gitlab, because they have the better
libre license etc on their service implementation.

Should I communicate this to you, or how should I do it?



>
> ;; This file is free software; you can redistribute it and/or modify
> ;; it under the terms of the GNU General Public License as published by
> ;; the Free Software Foundation; either version 3, or (at your option)
> ;; any later version.
>
> ;; This file is distributed in the hope that it will be useful,
> ;; but WITHOUT ANY WARRANTY; without even the implied warranty of
> ;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
> ;; GNU General Public License for more details.
>
> ;; You should have received a copy of the GNU General Public License
> ;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
>
> You could also, or instead, add a LICENSE file containing the text of the GPL-3. But if you only add that file, then the "or (at your option) any later version" bit won't be known.
>
> If this is all to noisy, then you could also add this to the header:
>
> ;; License: GPL-3+
>
> Please adjust these packages accordingly: dna-debug,dragbox,emmental,emsane,pocketcompletion,sh-proxy, andzen-mode`.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
Joakim Verona
joakim@verona.se
+46705459454

**Comment by tarsius** [comment]
> I will use ;; License: GPL-3+

I was just going to update that suggestion. You might want to use something a bit more verbose like

;; License: GNU General Public License version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version

**Comment by tarsius** [comment]
> I'm thinking of moving my things to Gitlab, because they have the better
> libre license etc on their service implementation.
>
> Should I communicate this to you, or how should I do it?

Yes, please let me know when the move is complete.

**Comment by jave** [comment]
Jonas Bernoulli <notifications@github.com> writes:

>  I'm thinking of moving my things to Gitlab, because they have the better
>  libre license etc on their service implementation.
>
>  Should I communicate this to you, or how should I do it?
>
> Yes, please let me know when the move is complete.

I updated the licenses and moved these repositories to gitlab.

| sh-proxy         | https://gitlab.com/jave/sh-proxy         |
| zen-mode         | https://gitlab.com/jave/zen-mode         |
| dna-debug        | https://gitlab.com/jave/dna-debug        |
| dragbox          | https://gitlab.com/jave/dragbox          |
| emmental         | https://gitlab.com/jave/emmental         |
| emsane           | https://gitlab.com/jave/emsane           |
| pocketcompletion | https://gitlab.com/jave/pocketcompletion |



>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
Joakim Verona
joakim@verona.se
+46705459454

**Comment by tarsius** [comment]
Thanks!

The `zen-mode` package seems to be empty.

**Comment by tarsius** [comment]
I meant to say the *repository* appears to be empty.

% git clone git@gitlab.com:jave/zen-mode.git
Cloning into 'zen-mode'...
GitLab: You are not allowed to download code from this project.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jave** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> I meant to say the repository appears to be empty.
>
> % git clone git@gitlab.com:jave/zen-mode.git
> Cloning into 'zen-mode'...
> GitLab: You are not allowed to download code from this project.
> fatal: Could not read from remote repository.
>
> Please make sure you have the correct access rights
> and the repository exists.

Funny, this works for me:
git clone git@gitlab.com:jave/zen-mode.git

I checked the access settings, and it is public.

Do you have the same problem accessing https://gitlab.com/jave/zen-mode
?



>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
Joakim Verona
joakim@verona.se
+46705459454

**Comment by tarsius** [comment]
Yes. Here is what happens when I clone pocketcompletion

[/tmp] % git clone https://gitlab.com/jave/pocketcompletion.git
Cloning into 'pocketcompletion'...
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 1), reused 0 (delta 0)
Unpacking objects: 100% (7/7), done.

And this is what happens when trying to clone zen-code:

[/tmp] % git clone https://gitlab.com/jave/zen-code.git        
Cloning into 'zen-code'...
Username for 'https://gitlab.com': tarsius
Password for 'https://tarsius@gitlab.com': 
remote: The project you were looking for could not be found.
fatal: repository 'https://gitlab.com/jave/zen-code.git/' not found

Also if I visit the repository in a browser, then there is no code and I am instead greeted with "This project does not have a wiki homepage yet".

**Comment by tarsius** [comment]
Ups, wrong url. But with the correct one it also does not work:

[/tmp] % git clone https://gitlab.com/jave/zen-mode.git
Cloning into 'zen-mode'...
Username for 'https://gitlab.com': tarsius
Password for 'https://tarsius@gitlab.com': 
remote: You are not allowed to download code from this project.
fatal: unable to access 'https://gitlab.com/jave/zen-mode.git/': The requested URL returned error: 403

**Comment by jave** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> Ups, wrong url. But with the correct one it also does not work:
>
> [/tmp] % git clone https://gitlab.com/jave/zen-mode.gitCloning into 'zen-mode'...
> Username for 'https://gitlab.com': tarsius
> Password for 'https://tarsius@gitlab.com':remote: You are not allowed to download code from this project.
> fatal: unable to access 'https://gitlab.com/jave/zen-mode.git/': The requested URL returned error: 403
>

Ok I verified I also got a 403.

Then I tried to go back to "private" and from there back to "public".

I dont get a 403 anymore. Can you verify?

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
Joakim Verona
joakim@verona.se
+46705459454

**Comment by tarsius** [comment]
I'm able to clone the repository too now. Thanks again.

**Comment by tarsius** [comment]
But it seems you haven't pushed the recent updates there yet.

**Comment by jave** [comment]
Jonas Bernoulli <notifications@github.com> writes:

> But it seems you haven't pushed the recent updates there yet.

There was this license line already:
;;License: GPL V3 or later

I added this as well now to please your parser:
;; License: GPL-3+

>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>
-- 
Joakim Verona
joakim@verona.se
+46705459454

**Comment by tarsius** [comment]
Thanks.

**Comment by tarsius** [comment]
I just noticed that you have not done this for `dired-sequence` itself yet (and that I forgot to list it above).

Could you please license this package too?
